### PR TITLE
Fixes for swift generator

### PR DESCRIPTION
**Pull request by epankratov**
We have introduced some clean-up in our api spec. Existing implementation of helium has small issue with output code.  Current PR fixes it.

### CODE REVIEW

**Comment by roman-mazur** [comment]
I see that parameters are excluded from body, but where are they added to URL query?

Also, it looks like we do not have any tests for this piece of code. We should add them.

**Comment by epankratov** [comment]
@roman-mazur They are added in formattedPathExtensionsForServiceMethod()

**Comment by roman-mazur** [comment]
What class?

Please add a test that checks how `parameters` are treated.

**Comment by epankratov** [comment]
I'll add all the missing tests

**Comment by roman-mazur** [comment]
Ok, looks better now. Merging.

**Pull request merged**
