### PR TITLE
Add Swift 3 support

### PR DESCRIPTION
**Pull request by evgenbakumenko**

### CODE REVIEW

**Comment by roman-mazur** [comment]
@evgenbakumenko could you please increment version here:
https://github.com/Keypr/helium/blob/master/build.gradle#L13

Otherwise, you will get troubles generating swift sources for legacy swift 2 parts of your project.

**Comment by roman-mazur** [comment]
Will do it myself :)

**Comment by evgenbakumenko** [comment]
@roman-mazur tests failing now `:command-line:swiftGenTestError: Unable to access jarfile build/libs/command-line-0.8.2-SNAPSHOT-nodeps.jar`

**Comment by roman-mazur** [comment]
Fixed

**Pull request merged**
